### ISSUE TITLE
Fix navigation for public view

### ISSUE THREAD

**Issue by kststudio** [codeforboston/urban-league-heat-pump-accelerator#68]
### Description
Under the public view, the navigation needs to be updated to work for both mobile, tablet, and desktop views.

### Screenshots
![navigation-desktop](https://user-images.githubusercontent.com/6118318/192663332-f6ba6341-1971-44cb-9148-8323dc7e95d2.jpg)
> Screenshot of the navigation in desktop view

![navigation-mobile](https://user-images.githubusercontent.com/6118318/192663343-109401db-77fc-446f-afd5-e6f12b017ad8.jpg)
> Screenshot of the navigation in mobile view

### Files
You can locate the Nav.js file here:
frontend > front > src > pages > Public > nav > Nav.js

**Optional files:**
frontend > front > src > pages > Public > PublicContainer.js
frontend > front > src > pages > Public > home > Home.js

### To Reproduce
- Make sure that you are on the frontend_dat branch by typing `git checkout frontend_dat` in the terminal
- After running the app via the terminal by typing `yarn start`, you should see the Selection Menu on the page
- Click the blue PUBLIC VIEW button
- You should now see the homepage. Use your browser dev tools to switch between mobile, tablet, and desktop views to reproduce the screenshots you see above

### Tasks
- [ ] ALL VIEWS: Add a CTA link/ button in the menu list. Consider a different CSS style.
- [ ] DESKTOP: Remove the hamburger icon
- [ ] TABLET: Remove the hamburger icon
- [ ] MOBILE: Remove the 3 menu links from being seen on the blue navbar
- [ ] MOBILE: Move the hamburger icon from the left side to the right side of the screen
- [ ] MOBILE: Make the hamburger icon clickable and toggle the 3 menu links. See the Helpful Resources on how to implement using MUI

When you are done, please create a pull request to merge into the frontend_dat branch.

### Helpful Resources
- [MUI navigation drawers](https://mui.com/material-ui/react-drawer/#main-content)

**Comment by johanna-j-c** [comment]
I'd like to work on this issue.
