### ISSUE TITLE
Update home page with real content

### ISSUE THREAD

**Issue by kststudio** [codeforboston/urban-league-heat-pump-accelerator#69]
### Description
Update the home page with real content that will be provided by Christopher. 

### Files
frontend > front > src > pages > Public > home > Home.js

### Tasks
- [ ] After receiving content, update the current home page with content
- [ ] After completion, create a full-page screenshot and send it to Christoper for review
- [ ] Optional: Create a dev site of the front end.
